version: '2'
services:
    nginx:
        image: nginx:latest
        ports:
            - "8081:80"
        volumes:
          - ./api/public:/srv/api/public:ro
          - ./api/docker/nginx/conf.d:/etc/nginx/conf.d
          - ./api/var/log/nginx:/var/log/nginx
        depends_on:
            - php
    php:
        build: ./api/docker/php
        links:
            - db_queue
        volumes:
            - ./api:/srv/api:rw,cached
    db_queue:
        restart: always
        image: mysql:8
        ports:
            - "23306:3306"
        volumes:
            - ./docker/db_queue/data:/var/lib/mysql
        # задаем пароль для root пользователя
        environment:
          MYSQL_DATABASE: db_queue
          MYSQL_USER: groonel
          MYSQL_PASSWORD: pus7MhrXFuUmtqvp
          MYSQL_ROOT_PASSWORD: pus7MhrXFuUmtqvp!
